<?php 
define("CONFIG_FILE_LOCATION", dirname(__FILE__) . DIRECTORY_SEPARATOR . 'config.php');
define("DB_FILE_LOCATION", dirname(__FILE__) . DIRECTORY_SEPARATOR . 'db' . DIRECTORY_SEPARATOR);
define("MODULE_FILE_LOCATION", dirname(__FILE__) . DIRECTORY_SEPARATOR . 'db' . DIRECTORY_SEPARATOR . 'modules');
define("TYPE_FILE_LOCATION", dirname(__FILE__) . DIRECTORY_SEPARATOR . 'db' . DIRECTORY_SEPARATOR . 'types');
define("LANG_FILE_LOCATION", dirname(__FILE__) . DIRECTORY_SEPARATOR . 'lang' . DIRECTORY_SEPARATOR);
define("FUNC_FILE_LOCATION", dirname(__FILE__) . DIRECTORY_SEPARATOR . 'lib' . DIRECTORY_SEPARATOR . 'func' . DIRECTORY_SEPARATOR);
define("CLASS_FILE_LOCATION", dirname(__FILE__) . DIRECTORY_SEPARATOR . 'lib' . DIRECTORY_SEPARATOR . 'classes' . DIRECTORY_SEPARATOR);
define("INC_FILE_LOCATION", dirname(__FILE__) . DIRECTORY_SEPARATOR . 'lib' . DIRECTORY_SEPARATOR . 'inc' . DIRECTORY_SEPARATOR);
define("TPL_FILE_LOCATION", dirname(__FILE__) . DIRECTORY_SEPARATOR . 'lib' . DIRECTORY_SEPARATOR . 'tpl' . DIRECTORY_SEPARATOR);

define("THEME_FILE_LOCATION", 'theme'); // to eventually remove
define("FULL_THEME_FILE_LOCATION", dirname(__FILE__) . DIRECTORY_SEPARATOR . THEME_FILE_LOCATION);
?>