<ul class="pageitem" id="home" title="<?php echo ($lang['home']); ?>">
	<li class="menu"><a id='menu_all' href="<?php echo ($config['url_path']); ?>/index.php?page=all"><img src="<?php echo ($config['url_path']);?>/theme/iPhone/images/menu_home_on.png"><span class="name"><?php echo ($lang['floorplan']); ?></a></span><span class="arrow"></span></a></li>    
	<li class="menu"><a id='menu_lights' href="<?php echo ($config['url_path']); ?>/index.php?page=lights"><img src="<?php echo ($config['url_path']);?>/theme/iPhone/images/menu_lights_on.png"><span class="name"><?php echo ($lang['lights']); ?></a></span><span class="arrow"></span></a></li>
	<li class="menu"><a id='menu_appliances' href="<?php echo ($config['url_path']); ?>/index.php?page=appliances"><img src="<?php echo ($config['url_path']);?>/theme/iPhone/images/menu_appliances_on.png"><span class="name"><?php echo ($lang['appliances']); ?></a></span><span class="arrow"></span></a></li>
	<li class="menu"><a id='menu_shutters' href="<?php echo ($config['url_path']); ?>/index.php?page=shutters"><img src="<?php echo ($config['url_path']);?>/theme/iPhone/images/menu_shutters_on.png"><span class="name"><?php echo ($lang['shutters']); ?></a></span><span class="arrow"></span></a></li>
	<li class="menu"><a id='menu_irrigation' href="<?php echo ($config['url_path']); ?>/index.php?page=irrigation"><img src="<?php echo ($config['url_path']);?>/theme/iPhone/images/menu_irrigation_on.png"><span class="name"><?php echo ($lang['irrigation']); ?></a></span><span class="arrow"></span></a></li>
	<li class="menu"><a id='menu_others' href="<?php echo ($config['url_path']); ?>/index.php?page=other"><img src="<?php echo ($config['url_path']);?>/theme/iPhone/images/menu_other_on.png"><span class="name"><?php echo ($lang['other']); ?></a></span><span class="arrow"></span></a></li>
	<li class="menu"><a id='menu_status' href="<?php echo ($config['url_path']); ?>/index.php?page=status"><img src="<?php echo ($config['url_path']);?>/theme/iPhone/images/menu_status_on.gif"><span class="name"><?php echo ($lang['heyustatus']);?></a></span><span class="arrow"></span></a></li>
	<li class="menu"><a id='menu_about' href="<?php echo ($config['url_path']); ?>/index.php?page=about"><img src="<?php echo ($config['url_path']);?>/theme/iPhone/images/menu_about_on.png"><span class="name"><?php echo ($lang['about']);?></a></span><span class="arrow"></span></a></li>
</ul>
